### ISSUE TITLE
Optional chaining not supported in Cypress base docker image

### ISSUE THREAD

**Issue by asset-web** [cypress-visual-regression/cypress-visual-regression#146]
I am trying to use your v2.0.0 plugin with cypress/included:12.1.0 docker image (node v16.x) from my JavaScript Cypress config.  However, the inclusion of `?.` optional chaining is not supported by default, throwing this error after upgrading from 1.7.0.

```
Error: Webpack Compilation Error
./node_modules/cypress-visual-regression/dist/command.js 22:52
Module parse failed: Unexpected token (22:52)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   }
| 
>   return getValueOrDefault(defaultScreenshotOptions?.errorThreshold, 0);
| }
| 
```
...
```
This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

Are there any plans for this line be re-written or the version of EMCA script to be defined in your plugin where possible to avoid the need to refactor existing test suites?
